name: Api
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/api2/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build, Lint & Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace api2 lint
      - run: yarn workspace api2 build
      - run: yarn workspace api2 test:debug
      - run: yarn workspace api2 test:e2e
      - run: echo "${{secrets.ROOT_ENV_TESTING }}" > .env
      - run: echo "${{secrets.API_ENV_TESTING }}" > packages/api2/.env
      - run: echo "${{secrets.DISCORDBOT_ENV_TESTING }}" > packages/discord-bot/.env
      - run: echo "${{secrets.FRONTEND_ENV_TESTING }}" > packages/frontend/.env
      - run: yarn mongodb:start
      - run: yarn workspace api2 test
