name: Discord-Bot
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/discord-bot/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build & Lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace api2 build
      - run: yarn workspace discord-bot lint
      - run: yarn workspace discord-bot build
